import { chromium } from "@playwright/test";
const browser = await chromium.launch({ args: ["--autoplay-policy=no-user-gesture-required"] });
const page = await browser.newPage({ viewport: { width: 1600, height: 950 } });
await page.addInitScript(() => localStorage.setItem("rebeat.settings", JSON.stringify({ state: { onboarded: true }, version: 1 })));
await page.goto("http://localhost:5173");
await page.getByTestId("audio-overlay").click();
await page.waitForTimeout(1500);
await page.evaluate(() => window.__rebeat.store.getState().setUi({ editSlotId: "slot-drop" }));
await page.getByText("Mixer", { exact: true }).click();
const client = await page.context().newCDPSession(page);
await client.send("Profiler.enable");
await page.keyboard.press("Space");
await page.waitForTimeout(500);
await client.send("Profiler.start");
await page.waitForTimeout(4000);
const { profile } = await client.send("Profiler.stop");
const self = new Map(); const byId = new Map(profile.nodes.map((n) => [n.id, n]));
let total = 0;
profile.samples.forEach((id, i) => { const n = byId.get(id); const k = `${n.callFrame.functionName || "(anon)"} ${n.callFrame.url.split("/").pop().split("?")[0]}:${n.callFrame.lineNumber}`; const d = (profile.timeDeltas[i] ?? 0) / 1000; total += d; self.set(k, (self.get(k) ?? 0) + d); });
console.log("total", total.toFixed(0), "ms");
console.log([...self.entries()].sort((a, b) => b[1] - a[1]).slice(0, 22).map(([k, v]) => `${v.toFixed(0).padStart(5)}ms ${k}`).join("\n"));
await browser.close();
